[build]
  command = 'npm run production && vendor/bin/jigsaw build production'
  publish = 'build_production'

[[redirects]]
  from = 'http://*'
  to = 'https://:splat'
  status = 301
  force = true

[[redirects]]
  from = 'https://phlak.netlify.com/*'
  to = 'https://www.phlak.net/:splat'
  status = 301
  force = true

[[redirects]]
  from = 'https://phlak.net/*'
  to = 'https://www.phlak.net/:splat'
  status = 301
  force = true

[[redirects]]
  from = 'https://phlak.dev/*'
  to = 'https://www.phlak.dev/:splat'
  status = 301
  force = true

# Project Redirects
[[redirects]]
  from = 'https://www.phlak.dev/colorizer'
  to = 'https://github.com/PHLAK/colorizer'
  status = 301
  force = true

[[redirects]]
  from = 'https://www.phlak.dev/config'
  to = 'https://github.com/PHLAK/Config'
  status = 301
  force = true

[[redirects]]
  from = 'https://www.phlak.dev/semver'
  to = 'https://github.com/PHLAK/SemVer'
  status = 301
  force = true

[[redirects]]
  from = 'https://www.phlak.dev/stash'
  to = 'https://github.com/PHLAK/Stash'
  status = 301
  force = true

[[redirects]]
  from = 'https://www.phlak.dev/strgen'
  to = 'https://github.com/PHLAK/strgen'
  status = 301
  force = true

[[redirects]]
  from = 'https://www.phlak.dev/twine'
  to = 'https://twine.phlak.net'
  status = 301
  force = true
