<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US">

<head>
    <title><?= $this->title; ?> | PHLAKNET</title>
    <link rel="shortcut icon" href="/images/icons/favicon.png" />

    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/css/style.css" />
    <? if($this->css): ?>
        <link rel="stylesheet" type="text/css" href="<?= $this->css; ?>" />
    <? endif; ?>

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap/bootstrap-dropdown.js"></script>
    
    <meta name="keywords" content="PHLAK, PHLAKNET, Chris Kankiewicz, Hacking, Code" />
</head>

<body>
    
    <div class="topbar" data-dropdown="dropdown">
      <div class="fill">
          
        <div class="container">
          <a class="brand" href="#"><span class="phlakGreen">PHLAK</span>NET</a>
          <ul class="nav">
            <li <?= $this->tab == 'home' ? 'class="active"' : false ?>><a href="/">Home</a></li>
            <li class="dropdown  <?= $this->tab == 'tools' ? 'active' : false ?>">
                <a href="#" class="dropdown-toggle">Toolbox</a>
                <ul class="dropdown-menu">
                    <li><a href="#">Secure Password Generator</a></li>
                    <li><a href="#">External IP Reporter</a></li>
                </ul>
            </li>
            <li <?= $this->tab == 'gallery' ? 'class="active"' : false ?>><a href="#">Image Gallery</a></li>
          </ul>
        </div>
        
      </div>
    </div>


    <div class="container">

        <div class="content">
            
            <div class="page-header">
                <h1>
                    <?= $this->title; ?>
                    <?php if ($this->subtitle): ?>
                        <small><?= $this->subtitle; ?></small>
                    <?php endif; ?>
                </h1>
            </div>
            
            <h1 id="page-title"></h1>
            
            <?= $this->layout()->content; ?>
            
        </div>

        <footer>
            <p>&copy; <?= date('Y'); ?> <a href="http://www.chriskankiewicz.com">Chris Kankiewicz</a></p>
        </footer>
    
    </div>
    
</div>


</body>
</html>
