<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US">

<head>
	<title><?= $this->title; ?> | PHLAKNET</title>
	<link rel="shortcut icon" href="/images/icons/favicon.png" />

	<link rel="stylesheet" type="text/css" href="/css/rebase-min.css" />
	<link rel="stylesheet" type="text/css" href="/css/style.css" />
	<? if($this->css): ?>
		<link rel="stylesheet" type="text/css" href="<?= $this->css; ?>" />
	<? endif; ?>

	<meta name="keywords" content="PHLAK, PHLAKNET, Chris Kankiewicz, Hacking, Code" />
</head>

<body>


<div id="wrap">
	<div id="main" class="clearfix">

		<div id="header">
			<div id="title"><a href="/"><span class="green">PHLAK</span>NET</a></div>
			<ul id="navigation">
				<li><a href="/scripts">Scripts</a></li>
				<li><a href="/ip">External IP</a></li>
				<li><a href="/image-gallery">Image Gallery</a></li>
				<li><a href="/about">About</a></li>
				<li><a href="/contact-us">Contact Us</a></li>
			</ul>
		</div>

		<div id="content">
			<h1 id="page-title"><?= $this->title; ?></h1>
			<?= $this->layout()->content; ?>
		</div>

		<a href="http://github.com/PHLAK/phlak.net" id="fork-me"><img src="/images/forkme.png" /></a>
	</div>
</div>

<div id="footer">
	<div class="floatLeft">Copyright &copy; <?= date('Y'); ?> &bull; PHLAKNET &bull; Some Rights Reserved</div>
	<div class="floatRight">Design by, <a href="http://www.chriskankiewicz.com">Chris Kankiewicz</a></div>
</div>


</body>
</html>
