<div id="twitchStream">
    <object type="application/x-shockwave-flash" height="507" width="854" id="live_embed_player_flash" data="http://www.twitch.tv/widgets/live_embed_player.swf?channel=lllphlaklll">
        <param name="allowFullScreen" value="true" />
        <param name="allowScriptAccess" value="always" />
        <param name="allowNetworking" value="all" />
        <param name="movie" value="http://www.twitch.tv/widgets/live_embed_player.swf" />
        <param name="flashvars" value="hostname=www.twitch.tv&amp;channel=lllphlaklll&amp;auto_play=true&amp;start_volume=25" />
    </object>
</div>
