<div class="row">
    
    <div class="span9">
        <div id="twitchStream">
            <object type="application/x-shockwave-flash"  width="640px" height="387px" id="twitchPlayer" data="http://www.twitch.tv/widgets/live_embed_player.swf?channel=lllphlaklll">
                <param name="allowFullScreen" value="true" />
                <param name="allowScriptAccess" value="always" />
                <param name="allowNetworking" value="all" />
                <param name="movie" value="http://www.twitch.tv/widgets/live_embed_player.swf" />
                <param name="flashvars" value="hostname=www.twitch.tv&amp;channel=lllphlaklll&amp;auto_play=true&amp;start_volume=50" />
            </object>
        </div>
    </div>
    
    <div class="span3">
        <div id="infoPane">
            <h3>Info</h3>
            <p>PHLAK has been a casual gamer his entire life owning several gaming consoles, his
            first being an original Game Boy. He started off his PC gaming career mostly with real
            time strategy games like Command &amp; Conquer: Red Alert, Age of Empires and StarCraft.
            After being introduced to Red Faction in high school, PHLAK took a particular interest 
            in first person shooters. He quickly discovered Counter-Strike, Half-Life and other
            Half-Life mods and has since become an avid fan the FPS genre. PHLAK enjoys nothing more
            than outsmarting another human being in a fast paced, online match.</p>
        
            <h3>Current Games</h3>
            <ul>
                <li>Battlefield 3</li>
                <li>Dota 2</li>
            </ul>
        </div>
    </div>
    
</div>
