<div class="row">
    
    <form action="#" method="post" id="passGenForm">
        
        <div class="clearfix">
        
            <label id="optionsCheckboxes">Character Set</label>
            
            <div class="input">
                <ul class="inputs-list">
                    
                    <li>
                        <label>
                            <input type="checkbox" name="charset[]" value="lower" checked />
                            <span rel="twipsy" title="a-z">Lower Alpha</span>
                        </label>
                    </li>
                    
                    <li>
                        <label>
                            <input type="checkbox" name="charset[]" value="upper" checked />
                            <span rel="twipsy" title="A-Z">Upper Alpha</span>
                        </label>
                    </li>
                    
                    <li>
                        <label>
                            <input type="checkbox" name="charset[]" value="num" checked />
                            <span rel="twipsy" title="0-9">Numbers</span>
                        </label>
                    </li>
                    
                    <li>
                        <label class="disabled">
                            <input type="checkbox" name="charset[]" value="special" />
                            <span rel="twipsy" title="! @ # $ % ^ &amp; * ( ) -_= + . ?">Special Characters</span>
                        </label>
                    </li>
                    
                    <li>
                        <label class="disabled">
                            <input type="checkbox" name="charset[]" value="extra" />
                            <span rel="twipsy" title="{ } [ ] < > : ; / \ | ~">Extra Characters</span>
                        </label>
                    </li>
                    
                </ul>
            </div>
            
        </div>
    
        <div class="clearfix">
            
            <label for="repeatChars">Repeat Characters</label>
            
            <div class="input">
                <select name="repeatChars" id="repeatChars" class="span2">
                    <option value="0">Yes</option>
                    <option value="1">No</option>
                </select>
            </div>
            
        </div>
        
        <div class="clearfix">
            
            <label for="length">Length</label>
            
            <div class="input">
                <input type="text" name="length"value="16" maxlength="2" id="length" class="span1" />
            </div>
            
        </div>
        
        <div class="actions">
            
            <button type="submit" id="passGenSubmit" class="btn primary">Generate Password</button>
            &nbsp;&nbsp;&nbsp;
            <input id="output" class="span6" type="text" placeholder="Your Password" name="output" />
            
        </div>
    
    </form>

</div>


<script type="text/javascript">

    $(document).ready(function () {
        
        $("[rel=twipsy]").twipsy({
            animate: true,
            live: true,
            offset: 5,
            placement: 'right'
        });
        
        $('#output').click(function() {
            $(this).select();
        });
        
    });

    $('#passGenForm').submit(function(event) {
        
        // Prevent form submitting normally
        event.preventDefault();
        
        // Set some variables
        var length  = $('#length').val();
        var strict  = $('#repeatChars').val();
        
        var charset = {};
        $('input[name="charset[]"]:checked').each(function(i, el) {
            charset[i] = $(el).val();
        });
        
        // Send the data using post and update the text field 
        $.post('/tools/secure-password-generator-post', {
                charset: charset,
                strict: strict,
                length: length
            },
            function(data) {
                $('#output').val(data);
            }
        );
        
    });
    
</script>