<div class="row">
    
    <form action="#" method="post" id="passGenForm">
        
        <div class="clearfix">
        
            <label id="optionsCheckboxes">Complexity Options</label>
            
            <div class="input">
                <ul class="inputs-list">
                    
                    <li>
                        <label>
                            <input type="checkbox" name="lowerAlpha" value="TRUE" />
                            <span rel="twipsy" title="a-z">Lower Alpha</span>
                        </label>
                    </li>
                    
                    <li>
                        <label>
                            <input type="checkbox" name="upperAlpha" value="TRUE" />
                            <span rel="twipsy" title="A-Z">Upper Alpha</span>
                        </label>
                    </li>
                    
                    <li>
                        <label>
                            <input type="checkbox" name="numbers" value="TRUE" />
                            <span rel="twipsy" title="0-9">Numbers</span>
                        </label>
                    </li>
                    
                    <li>
                        <label class="disabled">
                            <input type="checkbox" name="specialChars" value="TRUE" />
                            <span rel="twipsy" title="! @ # $ % ^ &amp; * ( ) -_= + . ?">Special Characters</span>
                        </label>
                    </li>
                    
                    <li>
                        <label class="disabled">
                            <input type="checkbox" name="extraChars" value="TRUE" />
                            <span rel="twipsy" title="{ } [ ] < > : ; / \ | ~">Extra Characters</span>
                        </label>
                    </li>
                    
                </ul>
            </div>
            
        </div>
    
        <div class="clearfix">
            
            <label for="repeatChars">Repeat Characters</label>
            
            <div class="input">
                <select name="repeatChars" id="repeatChars" class="span2">
                    <option>Yes</option>
                    <option>No</option>
                </select>
            </div>
            
        </div>
        
        <div class="clearfix">
            
            <label for="length">Length</label>
            
            <div class="input">
                <input class="span1" id="length" name="length" type="text" />
            </div>
            
        </div>
        
        <div class="actions">
            
            <button type="submit" id="passGenSubmit" class="btn primary">Generate Password</button>
            &nbsp;&nbsp;&nbsp;
            <input id="output" class="span6" type="text" placeholder="Your Password" name="output">
            
        </div>
    
    </form>

</div>


<script type="text/javascript">

    $(document).ready(function () {
        
        $("[rel=twipsy]").twipsy({
            animate: true,
            live: true,
            offset: 5,
            placement: 'right'
        });
        
    });

    $('#passGenForm').submit(function(event) {
        
        // Prevent form submitting normally
        event.preventDefault();
        
        // Set some variables
        var length = $('#length').val();
        
        // Send the data using post and update the text field 
        $.post('/tools/secure-password-generator-post', { length: length },
            function(data) {
                $('#output').val(data);
            }
        );
        
    });
    
</script>