<form action="#" method="post" id="passGenForm">
    <input type="checkbox" value="lowerAlpha" id="lowerAlpha" />Lower Alpha <pre>a-z</pre>
    <input type="checkbox" value="upperAlpha" id="upperAlpha" />Upper Alpha <pre>A-Z</pre>
    <input type="checkbox" value="numbers" id="numbers" />Numbers <pre>0-9</pre>
    <input type="checkbox" value="specialChars" id="specialChars" />Special Characters <pre>!@#$%^&amp;*()-_=+.?</pre>
    <input type="checkbox" value="extraChars" id="extraChars" />Extra Characters <pre>{}[]<>:;/\|~</pre>
    
    <label for="repeatChars">
        <div class="title">Dont repeat characters?</div>
        <input type="checkbox" value="repeatChars" id="repeatChars" />
    </label>
    
    <br/>
    
    <label for="length">
        <span class="passGenInlineTitle">Length: </span>
        <input type="text" maxlength="2" size="2" name="length" id="length" />
    </label>
        
    </label>
    
    <button type="submit" id="passGenSubmit">Generate Password</button>
</form>

<br/>

<textarea cols="40" rows="5" name="output" id="output"></textarea>

<script type="text/javascript">

    $('#passGenForm').submit(function(event) {
        
        // Prevent form submitting normally
        event.preventDefault();
        
        // Set some variables
        var length = $('#length').val();
        
        // Send the data using post and update the text field 
        $.post('/tools/secure-password-generator-post', { length: length },
            function(data) {
                $('#output').val(data);
            }
        );
        
    });
    
</script>